
services:
  - type: web
    name: helen-shop
    runtime: python
    buildCommand: pip install -r requirements.txt && python manage.py migrate && python manage.py collectstatic --noinput
    startCommand: gunicorn clothing_store.wsgi:application
    envVars:
      - key: DJANGO_ALLOWED_HOSTS
        value: helen-shop.onrender.com
      - key: DEBUG
        value: 'False'
    disk:
      name: helen-shop-media
      mountPath: /opt/render/project/src/media
      sizeGB: 1