# Generated by Django 6.0.3 on 2026-04-24 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Ссылка на изображение'),
        ),
    ]
